# Generated by Django 4.2.4 on 2023-08-10 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcadastrousuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
